name: Deploy Cloud Functions
on:
  push:
    branches:
      - master
    paths:
      - '/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "kilimanjaro-4c1b5.web.app"
          PROJECT_PATH: "./functions"
